## import everything

In [2]:
import psycopg2
import pandas as pd

In [3]:
train = pd.read_csv('train.csv')
train.head().T

/Users/jimseesel/.vir_env/lib/python2.7/site-packages/pandas/io/parsers.py:1170: DtypeWarning: Columns (8,9,10,11,12,43,157,196,214,225,228,229,231,235,238) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)

                  0          1          2          3          4
ID                2          4          5          7          8
VAR_0001          H          H          H          H          R
VAR_0002        224          7        116        240         72
VAR_0003          0         53          3        300        261
VAR_0004       4300       4448       3464       3200       2000
VAR_0005          C          B          C          C          N
VAR_0006          0          1          0          0          0
VAR_0007          0          0          0          0          0
VAR_0008      False      False      False      False      False
VAR_0009      False      False      False      False      False
VAR_0010      False      False      False      False      False
VAR_0011      False      False      False      False      False
VAR_0012      False      False      False      False      False
VAR_0013          0          1          0          0          0
VAR_0014          0          0          0          0          0
VAR_0015          0          1          0          0          0
VAR_0016          1          2          1          2          1
VAR_0017          0          1          0          0          0
VAR_0018          0          0          0          0          0
VAR_0019          0          0          0          0          0
VAR_0020          0          0          0          0          0
VAR_0021          0          0          0          0          0
VAR_0022          0          0          0          0          0
VAR_0023          0          0          0          0          0
VAR_0024          0          0          0          0          0
VAR_0025          0          0          0          0          0
VAR_0026          0          0          0          0          0
VAR_0027          0          0          0          0          0
VAR_0028          0          0          0          0          0
VAR_0029          0          0          0          0          0
...             ...        ...        ...        ...        ...
VAR_1906         98          2          3         98         98
VAR_1907         98          0          0         98         98
VAR_1908         98          0         97         98         98
VAR_1909         98          0          0         98         98
VAR_1910         98          0         97         98         98
VAR_1911        998          0        997        998        998
VAR_1912  999999998       6546  999999997  999999998  999999998
VAR_1913  999999998       6546  999999997  999999998  999999998
VAR_1914  999999998       6125  999999997  999999998  999999998
VAR_1915  999999998         76  999999997  999999998  999999998
VAR_1916        998          1          1        998        998
VAR_1917        998          1        997        998        998
VAR_1918       9998       9996       9996       9998       9998
VAR_1919       9998        111        113       9998       9998
VAR_1920          0          0          0          0          0
VAR_1921         98         98         98         98         98
VAR_1922  999999998  999999998  999999998  999999998  999999998
VAR_1923  999999998  999999998  999999998  999999998  999999998
VAR_1924       9998       9998       9998       9998       9998
VAR_1925          0          0          0          0          0
VAR_1926         98         98         98         98         98
VAR_1927         98         98         98         98         98
VAR_1928        998        998        998        998        998
VAR_1929  999999998  999999998  999999998  999999998  999999998
VAR_1930        998        998        998        998        998
VAR_1931        998        998        998        998        998
VAR_1932       9998       9998       9998       9998       9998
VAR_1933       9998       9998       9998       9998       9998
VAR_1934       IAPS       IAPS       IAPS        RCC     BRANCH
target            0          0          0          0          1

[1934 rows x 5 columns]

In [4]:
test = pd.read_csv('test.csv')
test.head().T

/Users/jimseesel/.vir_env/lib/python2.7/site-packages/pandas/io/parsers.py:1170: DtypeWarning: Columns (8,9,10,11,12,43,157,167,177,196,214,225,228,229,231,235,238) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)

                  0          1          2          3          4
ID                1          3          6          9         10
VAR_0001          R          R          R          R          H
VAR_0002        360         74         21          8         91
VAR_0003         25        192         36          2         39
VAR_0004       2251       3274       3500       1500      84500
VAR_0005          B          C          C          B          C
VAR_0006          2          2          1          0          8
VAR_0007          2          3          1          0          3
VAR_0008      False      False      False      False      False
VAR_0009      False      False      False      False      False
VAR_0010      False      False      False      False      False
VAR_0011      False      False      False      False      False
VAR_0012      False      False      False      False      False
VAR_0013          2          2          1          0          8
VAR_0014          2          3          1          0          3
VAR_0015          1          2          1          0          1
VAR_0016          2          2          1          1          5
VAR_0017          1          2          0          0          2
VAR_0018          0          0          0          0          0
VAR_0019          0          0          0          0          0
VAR_0020          0          0          0          0          0
VAR_0021          0          0          0          0          0
VAR_0022          0          0          0          0          0
VAR_0023          0          0          0          0          0
VAR_0024          0          0          0          0          0
VAR_0025          0          0          0          0          0
VAR_0026          0          0          0          0          0
VAR_0027          0          0          0          0          0
VAR_0028          0          0          0          0          0
VAR_0029          0          0          0          0          0
...             ...        ...        ...        ...        ...
VAR_1905          0         98         98          0         98
VAR_1906          4         98         98          2         98
VAR_1907          3         98         98          0         98
VAR_1908          0         98         98          0         98
VAR_1909          1         98         98          0         98
VAR_1910          0         98         98          0         98
VAR_1911          0        998        998          0        998
VAR_1912       6121  999999998  999999998  999999996  999999998
VAR_1913      49188  999999998  999999998      21362  999999998
VAR_1914       6121  999999998  999999998  999999996  999999998
VAR_1915         70  999999998  999999998  999999996  999999998
VAR_1916        400        998        998          1        998
VAR_1917          1        998        998          1        998
VAR_1918         47       9998       9998       9996       9998
VAR_1919         56       9998       9998          6       9998
VAR_1920          0          0          0          2          0
VAR_1921         98         98         98          1         98
VAR_1922  999999998  999999998  999999998       1140  999999998
VAR_1923  999999998  999999998  999999998      41300  999999998
VAR_1924       9998       9998       9998        381       9998
VAR_1925          0          0          0          0          0
VAR_1926         98         98         98         98         98
VAR_1927         98         98         98         98         98
VAR_1928        998        998        998        998        998
VAR_1929  999999998  999999998  999999998  999999998  999999998
VAR_1930        998        998        998        998        998
VAR_1931        998        998        998        998        998
VAR_1932       9998       9998       9998       9998       9998
VAR_1933       9998       9998       9998       9998       9998
VAR_1934       IAPS       IAPS       IAPS       IAPS       IAPS

[1933 rows x 5 columns]

In [5]:
train.to_pickle('train.pkl')
test.to_pickle('test.pkl')